file_to_disk = './tmp/disk1.vdi'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.12.13"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
    vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  end  
  #config.vm.provision :shell, :path => 'install.sh', privileged: false
end
